# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - '!release/*'
  pull_request:
    branches:
      - '!release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Code checkout
        uses: actions/checkout@v3

      # Install jdk
      - name: Install JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Install curl-dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Run Tests
        run: gradlew check
